#服务器配置
server:
  #端口
  port: 9983

#spring配置
spring:
  #应用配置
  application:
    #名称: OAuth2认证授权服务
    name: auth-server
  #数据库配置
  datasource:
    url: jdbc:mysql://47.104.172.218:3306/user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 4e3w4s3a
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      #host: 47.93.228.207
    host: 127.0.0.1
    port: 6379
mybatis:
  typeAliasesPackage: com.**.**.entity
  mapperLocations: classpath:com/**/**/mapper/*.xml

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://localhost:9980/eureka/
    #eureka client刷新本地缓存时间
    registryFetchIntervalSeconds: 5
  instance:
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 5


ribbon:
  eager-load:
    enabled: true
    clients: auth-server
  #eureka客户端ribbon刷新时间
  ServerListRefreshInterval: 5000

#安全配置
security:
  #oauth2配置
  oauth2:
    resource:
      filter-order: 3
