#服务器配置
server:
  #端口
  port: 9983
#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://localhost:9980/eureka/

#spring配置
spring:
  #应用配置
  application:
    #名称: OAuth2认证授权服务
    name: auth-server
  #数据库配置
  datasource:
    url: jdbc:mysql://47.104.172.218:3306/user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 4e3w4s3a
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.**.**.entity
  mapperLocations: classpath:com/**/**/mapper/*.xml

#安全配置
security:
  #oauth2配置
  oauth2:
    resource:
      filter-order: 3
