server:
  port: 9981
spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9980/eureka/
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    material-service:
      path: /material-service/**
      #敏感头信息
      sensitiveHeaders:
      serviceId: material-service
    auth-server:
      path: /auth-server/**
      sensitiveHeaders:
      serviceId: auth-server
  #添加代理头
  add-proxy-headers: true
  #是否开启重试功能
  retryable: true
#  ribbon:
#      eager-load:
#        enabled: true
#ribbon 重试时间
ribbon:
  #配置连接超
  ConnectTimeout: 7000
  #请求处理
  ReadTimeout: 15000
  OkToRetryOnAllOperations: true
  #同一个Server重试的次数(除去首次)
  MaxAutoRetries: 1
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 1
  okhttp:
      enabled: true
  eager-load:
    enabled: true
    clients: material-service,auth-server,user-service

#hystrix    熔断服务 转发等待时长
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

