#服务器配置
server:
  #端口
  port: 8084
  #启动压缩
  compression:
    enabled: true

#spring配置
spring:
  #应用配置
  application:
    #名称: material服务
    name: material-service
  #数据库配置
  datasource:
    url: jdbc:mysql://47.104.172.218:3306/material?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 4e3w4s3a
    driver-class-name: com.mysql.jdbc.Driver
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
  #404交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

#mybatis
mybatis:
  typeAliasesPackage: com.**.**.entity
  mapperLocations: classpath:com/**/**/mapper/*.xml

#日志级别
logging:
  level:
    com:
      mlink: debug

#swagger
pringfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://localhost:9980/eureka/
  #将swagger页面,集成到到eureka中心
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html


#安全配置(开发阶段注释,集成阶段打开)
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:9983/user
      prefer-token-info: false

#feign开启降级服务
feign:
  hystrix:
    enabled: true

#ribbon   开启Ribbon的饥饿加载模式
ribbon:
  eager-load:
    enabled: true
    #指定需要饥饿加载的客户端名称、服务名
    clients: user-service

#hystrix    熔断服务 转发等待时长
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


